# Generated by Django 4.0.4 on 2022-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(max_length=100)),
                ('barcode_type', models.CharField(max_length=100)),
            ],
        ),
    ]
