# Generated by Django 4.0.4 on 2022-04-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0006_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='medical.place')),
                ('parcels', models.ManyToManyField(to='medical.parcel')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='medical.place')),
            ],
        ),
    ]
