# Generated by Django 4.0.4 on 2022-04-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='updated_at',
            new_name='delivered_at',
        ),
    ]
