# Generated by Django 4.0.4 on 2022-04-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_alter_delivery_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.delivery')),
            ],
        ),
    ]
