# Generated by Django 4.0.4 on 2022-04-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_receit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receit',
            name='delivery',
        ),
        migrations.AddField(
            model_name='delivery',
            name='receit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.receit'),
        ),
    ]
