# Generated by Django 4.0.4 on 2022-04-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_alter_delivery_receit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='receit',
        ),
        migrations.AddField(
            model_name='receit',
            name='receit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receit', to='medical.delivery'),
        ),
    ]
