# Generated by Django 4.0.4 on 2022-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_remove_receit_receit_delivery_receit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
