# Generated by Django 4.0.4 on 2022-05-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0018_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receit',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receit', to='medical.delivery'),
        ),
    ]
